### ISSUE TITLE
derivative of gaussian

### ISSUE THREAD

**Issue by samrere** [UsamaI000/CannyEdgeDetection-from-scratch-python#1]
Hi thanks for your notebook!
I'm a new learner so I may be wrong, but if you print out the gx and gy, it looks like they are swapped? i.e. 
gx=
array([[ -19., -138.,  -19.],
       [   0.,    0.,    0.],
       [  19.,  138.,   19.]])

gy=
array([[ -19.,    0.,   19.],
       [-138.,    0.,  138.],
       [ -19.,    0.,   19.]])

**Comment by UsamaI000** [comment]
Yes, gx and gy should be opposite

**Comment by samrere** [comment]
Hi, what i mean is not that Gx and Gy are opposite, i.e. transpose of each
other. But Gx should be Gy and vice versa. If you check sobel operators in
Wikipedia, its Gx have a column of zeros whereas Gy a row of zeros.

**Comment by UsamaI000** [comment]
Yes, you are right. My mistake.

**Comment by UsamaI000** [comment]
Correct gx and gy should be

Gy=

array([[ -19., -138., -19.],

[ 0., 0., 0.],
[ 19., 138., 19.]])

gx=
array([[ -19., 0., 19.],
[-138., 0., 138.],
[ -19., 0., 19.]])

**Comment by samrere** [comment]
Got it. Thank you:)

**Comment by UsamaI000** [comment]
No problem
